// request.http

### Obtener Lista de Productos
GET http://localhost:3000/productos

### Obtener Lista de Facturas
GET http://localhost:3000/facturas

### Obtener una factura
GET http://localhost:3000/facturas/1

### Obtener Lista de Pedidos
GET http://localhost:3000/pedidos

### Obtener Un  Pedido
GET http://localhost:3000/pedidos/1

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "admin1",
  "password": "adminhash"
}

### Obtener Lista de notificationes
GET http://localhost:3000/notificaciones