// request.http
### Crear una persona y asignarla como alumno
POST http://localhost:3000/personas/crear-alumno
Content-Type: application/json

{
  "nombre": "Juaniyoa",
  "apellido": "Pereza",
  "tipo_documento": "CI",
  "nro_documento": "123452",
  "telefono": "123456789",
  "email": "juan.perez1@example.com",
  "direccion": "Calle Faalsa 123",
  "codigo_alumno": "A004",
  "observaciones": "Estudiante flojo"
}

### Obtener lista de alumnos
GET http://localhost:3000/personas/alumnos
