// request.http
### Crear una persona y asignarla como alumno
POST http://localhost:3000/personas/crear-alumno
Content-Type: application/json

{
  "nombre": "Juaniyoa",
  "apellido": "Pereza",
  "tipo_documento": "CI",
  "nro_documento": "123452",
  "telefono": "123456789",
  "email": "juan.perez1@example.com",
  "direccion": "Calle Faalsa 123",
  "codigo_alumno": "A004",
  "observaciones": "Estudiante flojo"
}

### Obtener lista de alumnos
GET http://localhost:3000/personas/alumnos

### Obtener lista de módulos con referencias internas
GET http://localhost:3000/modulos
Accept: application/json

### Inscribir a un alumno en un módulo
POST http://localhost:3000/inscripciones
Content-Type: application/json

{
    "id_alumno": 4,
    "id_modulo": 1
}

### Obtener lista de alumnos inscritos en un módulo
GET http://localhost:3000/inscripciones/modulo/1
